c_compiler:                # [win]
  - vs2022                 # [win]
cxx_compiler:              # [win]
  - vs2022                 # [win]
channel_sources:
  - realthunder,conda-forge,defaults
channel_targets:
  - realthunder main
