build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: false
os_version:
  linux_64: cos7
github:
  user_or_org: realthunder
  branch_name: main
  tooling_branch_name: main
provider:
  linux_64: github_actions
  linux_aarch64: github_actions
  win_64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
test: native_and_emulated
